### PR TITLE
Remove the extra single-quotes to retrieve git config on Windows

### LINKED ISSUE #8: Lab can not get any Git config on Windows
When using lab.el out-of-the-box on Windows, everything it tries to read from my `.gitconfig`, results in the message: `"error: invalid key: 'remote.origin.url'"`. When I debugged the code, it seemed that I had to remove the `'` around `%s` before getting lab.el to work on Windows. On MacOS it works with `'` and without `'` around `%s`.

```elisp

(defun lab-git-get-config (conf)
  "`git config --get CONF' wrapper."
  (thread-last
    (format "git config --get '%s'" conf)
    shell-command-to-string
    s-trim))
```

### PR DESCRIPTION
**Pull request by sebastiaanspeck**
Fixes #8

### CODE REVIEW

**Comment by isamert** [comment]
Windows is weird about shell quoting I guess. Probably the right way to fix this would be something like:

```elisp
(defun lab-git-get-config (conf)
  "`git config --get CONF' wrapper."
  (s-trim
   (with-temp-buffer
     (call-process "git" nil t nil "config" "--get" conf)
     (buffer-string))))
```

But maybe Windows will also complain about this. I'll merge the PR but can you also confirm the above snippet works in Windows?

**Comment by sebastiaanspeck** [comment]
> Windows is weird about shell quoting I guess. Probably the right way to fix this would be something like:
> 
> ```elisp
> (defun lab-git-get-config (conf)
>   "`git config --get CONF' wrapper."
>   (s-trim
>    (with-temp-buffer
>      (call-process "git" nil t nil "config" "--get" conf)
>      (buffer-string))))
> ```
> 
> But maybe Windows will also complain about this. I'll merge the PR but can you also confirm the above snippet works in Windows?

Hi, first of all, thanks for merging my quick-fix. I've tested the above snippet and that indeed works perfectly for Windows. If you want, I can open a new PR to implement it like that.

**Comment by sebastiaanspeck** [comment]
I've found some more `'%s'` in the rest of the package. I haven't checked if these have the same "bug" in Windows: https://github.com/search?q=repo%3Aisamert%2Flab.el%20%27%25s%27&type=code.

- The command `fd` does not exist on Windows. `find` and `dir` does.
- The `lab-git-origin-switch-to-ssh` works, but changed to url to `'git@...'`. Besides that, the function itself retrieves the URL directly – `(https-origin (s-trim (shell-command-to-string "git config --get remote.origin.url")))` –why not via `lab-git-get-config`?

**Comment by isamert** [comment]
Sorry for getting back late, somehow it slipped through my inbox.

Thanks for inspection, I fixed them as you've recommended. As for the `fd` binary, it's an [external program that you can install](https://github.com/sharkdp/fd). I think the Windows find is completely different from Unix find, so fd is a nice middle ground that supports both of the systems.

**Comment by sebastiaanspeck** [comment]
I've found another one that uses `'%s'`:
https://github.com/isamert/lab.el/blob/193eb6b74f4c60c455cae276d3881668383b21fc/lab.el#L653

And it fails:
```
fatal: protocol ''https' is not supported
>> Cloning https://github.com/isamert/lab.el.git to c:/Users/sspeck/Downloads/lab.el...
```

Un-quoting was the fix again.

**Comment by isamert** [comment]
Thanks for letting me know! I went over other shell command calls and I believe this was the last one :). Instead of un-quoting, I went with the double-quotes as some shells may have problems with the `:` character. Let me know if there are any problems.

**Pull request merged**
